#!/bin/sh

set -e

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"

filesToFormat="$(git diff --cached --name-only --diff-filter=ACMR | awk '$1 ~ /\.kts|\.java|\.kt/ { print $1}')"

for sourceFilePath in $filesToFormat
do
    echo "${REPO_ROOT_DIR}"
    "${REPO_ROOT_DIR}/gradlew" spotlessApply -PspotlessIdeHook="${REPO_ROOT_DIR}/${sourceFilePath}"
    git add $sourceFilePath
done;